buildscript {
  dependencies {
    classpath("org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin:${kotlinVersion}")
  }
}

plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

apply plugin: 'org.jetbrains.kotlin.plugin.compose'

group = 'expo.modules.widgetbridge'
version = '1.0.0'

android {
  namespace "expo.modules.widgetbridge"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "androidx.glance:glance-appwidget:1.1.1"
  implementation "androidx.glance:glance-material3:1.1.1"
}
